name             'rb-selinux'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-rb-selinux'
issues_url       'https://github.com/redBorder/cookbook-rb-selinux/issues'
source_url       'https://github.com/redBorder/cookbook-rb-selinux'
chef_version     '>= 15.0'
supports         'rocky', '>= 9.0'
version          '0.1.1'
